### ISSUE TITLE
An error occurred: Error: Failed to load shared library:

### ISSUE THREAD

**Issue by ensar65** [Sahil1337/node-tls-client#2]
first try on my ubuntu pc its says process.stdout.clearLine is not function after try on my windows pc its says:

C:\Users\ensare\Desktop\tlstet>node index.js
An error occurred: Error: Failed to load shared library: İşlem başarıyla tamamlandı.
    at obj.load (C:\Users\ensare\Desktop\tlstet\node_modules\koffi\index.js:480:27)
    at load (C:\Users\ensare\Desktop\tlstet\node_modules\node-tls-client\dist\utils\koffi.js:24:34)
    at Client.init (C:\Users\ensare\Desktop\tlstet\node_modules\node-tls-client\dist\lib\Client.js:15:46)
    at Object.<anonymous> (C:\Users\ensare\Desktop\tlstet\node_modules\node-tls-client\dist\utils\worker.js:12:8)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^
Error: Failed to load shared library: İşlem başarıyla tamamlandı.
    at obj.load (C:\Users\ensare\Desktop\tlstet\node_modules\koffi\index.js:480:27)
    at load (C:\Users\ensare\Desktop\tlstet\node_modules\node-tls-client\dist\utils\koffi.js:24:34)
    at Client.init (C:\Users\ensare\Desktop\tlstet\node_modules\node-tls-client\dist\lib\Client.js:15:46)
    at Object.<anonymous> (C:\Users\ensare\Desktop\tlstet\node_modules\node-tls-client\dist\utils\worker.js:12:8)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

**Comment by Sahil1337** [comment]
Fixed in [this](https://github.com/Sahil1337/node-tls-client/pull/9) pull request.
