### ISSUE TITLE
Error While Fetching shared library url

### ISSUE THREAD

**Issue by ziad-gg** [Sahil1337/node-tls-client#3]
First Run
```
@ziad-gg ➜ /workspaces/funcap (main) $ node test.js
@node-tls-client ~ DEBUG: Fetched latest version: v1.7.10
@node-tls-client ~ DEBUG: Fetched shared library url
An error occurred: TypeError [Error]: process.stdout.clearLine is not a function
    at Download.progress (/workspaces/funcap/node_modules/node-tls-client/dist/utils/download.js:69:24)
    at IncomingMessage.<anonymous> (/workspaces/funcap/node_modules/node-tls-client/dist/utils/download.js:93:30)
    at IncomingMessage.emit (node:events:530:35)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at HTTPParser.parserOnBody (node:_http_common:130:24)
    at TLSSocket.socketOnData (node:_http_client:544:22)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
 ```
 
if i run it again
```
@ziad-gg ➜ /workspaces/funcap (main) $ node test.js
Bus error (core dumped)
```

**Comment by ensar65** [comment]
temporary u can delete stdouts on node_modules file 
and then u need rm ```rm /tmp/tls-client-x64.so```
and restart code

**Comment by ziad-gg** [comment]
> temporary u can delete stdouts on node_modules file and then u need rm `rm /tmp/tls-client-x64.so` and restart code

Worked thank u

i think node.js removed
process.stdout.clearLine(0) &
process.stdout.cursorTo(0);

which shows that error for me

i am using node `v20.18.1`

**Comment by Sahil1337** [comment]
Fixed in [this](https://github.com/Sahil1337/node-tls-client/pull/9) pull request.
